[package]
name = "himalaya"
description = "CLI to manage emails"
version = "2.1.0"
authors = ["Clément DOUIN (soywod) <pimalaya.org@posteo.net>"]
rust-version = "1.89"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities", "email"]
keywords = ["cli", "email", "imap", "maildir", "sieve", "smtp"]
homepage = "https://pimalaya.org"
repository = "https://github.com/pimalaya/himalaya"

[features]
default = ["rustls-ring", "imap", "smtp", "sieve", "jmap", "gmail", "msgraph", "maildir"]
imap = ["dep:io-imap", "dep:mail-parser", "dep:rfc2047-decoder", "io-imap/client"]
jmap = ["dep:base64", "dep:io-jmap", "dep:mail-parser", "io-jmap/client", "io-jmap/schemars"]
gmail = ["dep:io-gmail", "dep:mail-parser", "io-gmail/client", "io-gmail/schemars"]
msgraph = ["dep:io-msgraph", "dep:mail-parser", "io-msgraph/client", "io-msgraph/schemars"]
smtp = ["dep:io-smtp", "dep:mail-parser"]
sieve = ["dep:io-managesieve", "io-managesieve/client", "io-managesieve/scram"]
maildir = ["dep:convert_case", "dep:io-maildir", "dep:mail-parser", "io-maildir/client", "io-maildir/parser"]
m2dir = ["dep:convert_case", "dep:io-m2dir", "dep:mail-parser", "io-m2dir/client"]
pimdir = ["dep:io-pimdir", "dep:io-replica", "dep:mail-parser"]
native-tls = ["pimalaya-stream/native-tls", "io-pim-discovery/native-tls", "io-imap?/native-tls", "io-jmap?/native-tls", "io-gmail?/native-tls", "io-msgraph?/native-tls", "io-smtp?/native-tls", "io-managesieve?/native-tls"]
rustls-aws = ["pimalaya-stream/rustls-aws", "io-pim-discovery/rustls-aws", "io-imap?/rustls-aws", "io-jmap?/rustls-aws", "io-gmail?/rustls-aws", "io-msgraph?/rustls-aws", "io-smtp?/rustls-aws", "io-managesieve?/rustls-aws"]
rustls-ring = ["pimalaya-stream/rustls-ring", "io-pim-discovery/rustls-ring", "io-imap?/rustls-ring", "io-jmap?/rustls-ring", "io-gmail?/rustls-ring", "io-msgraph?/rustls-ring", "io-smtp?/rustls-ring", "io-managesieve?/rustls-ring"]
vendored = ["pimalaya-stream/vendored"]

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"

[build-dependencies]
pimalaya-cli = { version = "0.2", default-features = false, features = ["build"] }

[dependencies]
anyhow = "1"
ariadne = "0.6"
base64 = { version = "0.23", optional = true }
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
chumsky = { version = "0.13", default-features = false }
clap = { version = "4.4", features = ["derive", "env", "wrap_help"] }
comfy-table = "8"
convert_case = { version = "0.11", optional = true }
crossterm = { version = "0.29", default-features = false, features = ["serde"] }
dirs = "6"
humansize = "2"
io-gmail = { version = "0.3", default-features = false, optional = true }
io-imap = { version = "0.6", default-features = false, optional = true }
io-jmap = { version = "0.3", default-features = false, optional = true }
io-m2dir = { version = "0.2", default-features = false, optional = true }
io-maildir = { version = "0.3", default-features = false, optional = true }
io-managesieve = { version = "0.1", default-features = false, optional = true }
io-msgraph = { version = "0.3", default-features = false, optional = true }
io-pim-discovery = { version = "0.7", default-features = false, features = ["autoconfig", "pacc", "rfc6186", "rfc8620"] }
io-pimdir = { version = "0.2", default-features = false, features = ["client"], optional = true }
io-replica = { version = "0.3", default-features = false, optional = true }
io-sasl = { version = "0.1", default-features = false, features = ["scram"] }
io-smtp = { version = "0.3", default-features = false, optional = true }
log = "0.4"
mail-builder = "0.5"
mail-parser = { version = "0.11", features = ["full_encoding", "serde"], optional = true }
mime_guess = "2"
open = "5"
percent-encoding = "2"
pimalaya-cli = { version = "0.2", default-features = false, features = ["terminal", "table", "prompt", "wizard", "imap", "smtp", "jmap", "spinner"] }
pimalaya-config = { version = "0.1", default-features = false, features = ["toml", "secret"] }
pimalaya-stream = { version = "0.3", default-features = false, features = ["std"] }
rfc2047-decoder = { version = "1", optional = true }
schemars = { version = "1", features = ["chrono04"] }
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
shellexpand = "3.1"
toml = "1.1"
url = { version = "2.2", features = ["serde"] }

[target.'cfg(windows)'.dependencies]
uds_windows = "1"
