[sources]
allow-git = [
  "https://github.com/nlnetlabs/domain",
  "https://github.com/pimalaya/io-email",
  "https://github.com/pimalaya/io-imap",
  "https://github.com/pimalaya/pimconf",
]
unknown-git = "deny"
unknown-registry = "deny"

[licenses]
allow = [
  "0BSD",
  "Apache-2.0 WITH LLVM-exception",
  "Apache-2.0",
  "BSD-3-Clause",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "Zlib",
]
