name: Fastmail tests

on:
  push:
    branches:
      - v2

jobs:
  fastmail-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --no-default-features --features jmap,rustls-ring --test fastmail-jmap -- --ignored
        env:
          FASTMAIL_EMAIL: ${{ secrets.FASTMAIL_EMAIL }}
          FASTMAIL_API_TOKEN: ${{ secrets.FASTMAIL_API_TOKEN }}
      - run: cargo test --no-default-features --features imap,rustls-ring --test fastmail-imap -- --ignored
        env:
          FASTMAIL_EMAIL: ${{ secrets.FASTMAIL_EMAIL }}
          FASTMAIL_APP_PASSWORD: ${{ secrets.FASTMAIL_APP_PASSWORD }}
      - run: cargo test --no-default-features --features smtp,rustls-ring --test fastmail-smtp -- --ignored
        env:
          FASTMAIL_EMAIL: ${{ secrets.FASTMAIL_EMAIL }}
          FASTMAIL_APP_PASSWORD: ${{ secrets.FASTMAIL_APP_PASSWORD }}
