name: Fastmail SMTP tests

on:
  push:
    branches:
      - v2

jobs:
  fastmail-smtp-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --no-default-features --features smtp,rustls-ring --test fastmail-smtp -- --ignored
        env:
          FASTMAIL_EMAIL: ${{ secrets.FASTMAIL_EMAIL }}
          FASTMAIL_APP_PASSWORD: ${{ secrets.FASTMAIL_APP_PASSWORD }}
