name: Stalwart JMAP tests

on:
  push:
    branches:
      - v2

jobs:
  stalwart-jmap-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: docker run -d --rm --name stalwart-test-for-himalaya -p 8080:8080 stalwartlabs/stalwart:latest-alpine
      - run: sleep 1
      - run: |
          echo "ADMIN_PASSWORD=$(docker logs stalwart-test-for-himalaya 2>&1 | grep -oP "(?<=with password ')[^']+")" >> $GITHUB_ENV
      - run: |
          curl -X POST \
               -u "admin:${ADMIN_PASSWORD}" \
               -H 'Content-Type: application/json' \
               -d '{"type":"domain","name":"pimalaya.org"}' \
               http://localhost:8080/api/principal
      - run: |
          curl -X POST \
               -u "admin:${ADMIN_PASSWORD}" \
               -H 'Content-Type: application/json' \
               -d '{"type":"individual","name":"test","emails":["test@pimalaya.org"],"secrets":["test"],"roles":["user"]}' \
               http://localhost:8080/api/principal
      - run: cargo test --no-default-features --features jmap,rustls-ring --test stalwart-jmap -- --ignored
      - run: docker stop stalwart-test-for-himalaya
