name: Stalwart IMAP tests

on:
  push:
    branches:
      - v2

jobs:
  stalwart-imap-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: ./tests/stalwart.sh
      - run: cargo test --no-default-features --features imap,rustls-ring --test stalwart-imap -- --ignored
      - run: docker stop himalaya-tests
